---
title: "preprocessing"
format: html
---

## Loading Data

```{r}
# read excel as dataframe, and consider all blank, "NA", and "N/A" as NA type for R
conf_data <- readxl::read_excel("../data/data.xlsx", na = c("", "NA", "N/A"))
```


## Network Analysis

### Filter Speech

```{r}
speech_filter <- conf_data |>
  # merge Presentation_TextX into a "speech" column
  unite("speech",
        Presentation_Text1,
        Presentation_Text2,
        Presentation_Text3,
        Presentation_Text4,
        na.rm = T) |> # remove the empty columns
  # filter the dataframe to only include the following columns
  select(
    cyear = Conference_Year,
    ctitle = Conference_Title,
    speaker = Person,
    speech) |>
  mutate(speech = na_if(speech, "")) |> # second check to drop empty "speech" rows
  group_by(cyear, ctitle, speaker) |> # grouping setup for below
  mutate(sid = row_number()) |> # set unique IDs for speakers who have multiple speeches in one conference
  ungroup() |> # undos orignal grouping
  drop_na()
```

### Preprocessing

```{r}
#| include: False
library(tidytext)
library(textstem)
library(textclean)
```

#### Expand Contractions

```{r}
speech_filter$speech <- speech_filter$speech |>
  replace_contraction() # splits contractions, ie can't -> can not
```

#### Lemmatization and Filter Stop Words and Digits

```{r}
cleaned_speech <- speech_filter |>
  unnest_tokens(output = word, input = speech) |> # turn speech into words
  filter(!str_detect(word, "\\d")) |> # filter out numbers using regex
  mutate(word = str_remove(word, "^_+"), # filters out strings that contains underscores
         lemma = lemmatize_words(word)) |> # adds a column for the lemmatized words, "lemma", ie runs, ran -> run
  anti_join(stop_words, by = c("lemma" = "word")) |> # removes stop words if the word is in the "lemma" column
  group_by(cyear, ctitle, speaker, sid) |> # primary key grouping (uniquely identify each speech)
  summarize(speech = paste(lemma, collapse = " "), .groups = "drop") |> # combine words back into speech
  ungroup() # undos prior grouping
```

#### N-Grams

```{r}
unigrams <- cleaned_speech |>
  unnest_tokens(output = word, input = speech) # splits speech into individual words, unigrams

bigrams <- cleaned_speech |>
  unnest_tokens(output = word, input = speech, token = "ngrams", n = 2) # splits speech into bigrams

trigrams <- cleaned_speech |>
  unnest_tokens(output = word, input = speech, token = "ngrams", n = 3) # splits speech into trigrams
```
