---
title: "170a_capstone_project"
format: html
editor: visual
---

## Loading Libraries

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(eurostat)

```

## Loading Data

```{r}

conf_data <- readxl::read_excel("WCF Presenters_Stats170_20260219.xlsx", na = c("", "NA", "N/A"))

```

## Task 1) Table listing total number of speakers/sponsors from each country

```{r}
#TODO: filter out
speaker_sponsor_filter = c("Presenter", "Sponsor", "Speaker", "Panelist", "Seminar", #Pretty Confident
                           "Workshop") #Less Confident

#NOTE: not sure if we should filter out people by speaker/sponsor role
speakers_per_country <- conf_data |> 
  group_by(Organization_Country) |>
  summarize(Total_Count = n_distinct(Person)) |>
  arrange(desc(Total_Count))

top_20 <- head(speakers_per_country, 20)
other_countries <- tail(speakers_per_country, nrow(speakers_per_country) - 20) |>
  summarize(Organization_Country = "Other Countries", 
            Total_Count = sum(Total_Count))

speaker_table <- bind_rows(top_20, other_countries)
print(speaker_table, n = Inf)


```

## Task 2) Condensed Dataframe for speakers by country category by conference year

```{r}
#| message: false

european_countries <- as.data.frame(eu_countries$name) |>
  rename("name" = "eu_countries$name")

# Adding the European diaspora countries
european_countries <- european_countries |>
  add_row(tibble(name = c("Russia", "Australia", "New Zealand", "Canada")))

three_country_speakers <- conf_data |>
  mutate(Region = case_when(
    Organization_Country %in% c("United States") ~ "United States",
    Organization_Country %in%  european_countries ~ "European Countries",
    TRUE ~ "Other Countries")) |>
  group_by(Conference_Year, Region) |>
  summarize(Total_Count = n_distinct(Person))
  
print(three_country_speakers)

```

## Task 3) Stacked Area Plot

```{r}
# NOTE:only has '97, '99, '04, '07, '09, 2012, 2013, so looks choppy
ggplot(three_country_speakers, aes(x = Conference_Year, y = Total_Count, fill = Region)) +
  geom_area(position = "fill", colour = "black", size = .2, alpha = .4) +
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Speaker Composition by Year",
    x =  "Conference_Year",
    y = "Percentage of Speakers"
  ) + 
  theme(plot.title = element_text(hjust = 0.5))

```

## Network Analysis

### Filter Speech

```{r}
speech_filter <- conf_data |>
  # merge Presentation_TextX into a "speech" column
  unite("speech",
        Presentation_Text1,
        Presentation_Text2,
        Presentation_Text3,
        Presentation_Text4,
        na.rm = T) |> # remove the empty columns
  # filter the dataframe to only include the following columns
  select(
    cyear = Conference_Year,
    ctitle = Conference_Title,
    speaker = Person,
    speech) |>
  mutate(speech = na_if(speech, "")) |> # second check to drop empty "speech" rows
  group_by(cyear, ctitle, speaker) |> # grouping setup for below
  mutate(sid = row_number()) |> # set unique IDs for speakers who have multiple speeches in one conference
  ungroup() |> # undos orignal grouping
  drop_na()
```

### Preprocessing

```{r}
#| include: False
library(tidytext)
library(textstem)
library(textclean)
```

#### Expand Contractions

```{r}
speech_filter$speech <- speech_filter$speech |>
  replace_contraction() # splits contractions, ie can't -> can not
```

#### Lemmatization and Filter Stop Words and Digits

```{r}
cleaned_speech <- speech_filter |>
  unnest_tokens(output = word, input = speech) |> # turn speech into words
  filter(!str_detect(word, "\\d")) |> # filter out numbers using regex
  mutate(word = str_remove(word, "^_+"), # filters out strings that contains underscores
         lemma = lemmatize_words(word)) |> # adds a column for the lemmatized words, "lemma", ie runs, ran -> run
  anti_join(stop_words, by = c("lemma" = "word")) |> # removes stop words if the word is in the "lemma" column
  group_by(cyear, ctitle, speaker, sid) |> # primary key grouping (uniquely identify each speech)
  summarize(speech = paste(lemma, collapse = " "), .groups = "drop") |> # combine words back into speech
  ungroup() # undos prior grouping
```

#### N-Grams

```{r}
unigrams <- cleaned_speech |>
  unnest_tokens(output = word, input = speech) # splits speech into individual words, unigrams

bigrams <- cleaned_speech |>
  unnest_tokens(output = word, input = speech, token = "ngrams", n = 2) # splits speech into bigrams

trigrams <- cleaned_speech |>
  unnest_tokens(output = word, input = speech, token = "ngrams", n = 3) # splits speech into trigrams
```
