---
title: "preprocessing"
format: html
---

## Loading Data

```{r}
library(tidyverse)
library(eurostat)
library(here)
library(stringr)

conf_data <- readxl::read_excel(here("data/raw", "new_data.xlsx"), na = c("", "NA", "N/A"), col_types = "text")
```


## Network Analysis

### Filter Speech

```{r}
speech_filter <- conf_data |>
  unite("speech",
        Presentation_Text1,
        Presentation_Text2,
        Presentation_Text3,
        Presentation_Text4,
        na.rm = T) |>
  select(
    year = Conference_Year,
    speaker = Person,
    speech) |>
  mutate(speech = na_if(speech, "")) |>
  mutate(speaker = speaker |>
           str_to_lower() |>
           str_trim()
         ) |>
  drop_na() |>
  group_by(speaker) |>
  mutate(speaker_id = cur_group_id()) |>
  ungroup() |>
  mutate(speech_id = row_number()) |>
  select(
    speech_id,
    speaker_id,
    speaker,
    year,
    speech
  )
```

### Preprocessing

```{r}
#| include: False
library(tidytext)
library(textstem)
library(textclean)
```

#### Expand Contractions

```{r}
speech_filter$speech <- speech_filter$speech |>
  replace_contraction()
```

#### Filter Stop Words and Digits

```{r}
cleaned_speech <- speech_filter |>
  unnest_tokens(output = word, input = speech) |>
  filter(!str_detect(word, "\\d")) |>
  mutate(word = str_remove(word, "^_+")) |>
  anti_join(stop_words, by = "word") |>
  group_by(cyear, ctitle, speaker, sid) |>
  summarize(speech = paste(word, collapse = " "), .groups = "drop") |>
  ungroup()
```

#### Output

```{r}
write.csv(speech_filter, "../data/processed/new_speeches.csv", row.names = F)
```

